### ISSUE TITLE
Stopping guard doesn't always kill webpack --watch

### ISSUE THREAD

**Issue by blainekasten** [gisikw/guard-webpack#1]
I haven't really triggered what is causing it. But i'm finding that when i'm kiling guard and starting it again, zombie webpack's are running still.

**Comment by gisikw** [comment]
Thanks for catching this! I was able to reproduce by `kill -9`'ing my Guard instance.

Looks like behavior should work properly when Guard is stepped down via `$ exit`, but if the parent thread is halted, we're not doing anything to ensure that child process is eliminated.

Should be able to get this fixed shortly :)

**Comment by gisikw** [comment]
@blainekasten Should be working correctly now in master. Mind pulling it down and checking your use case before I close this up?

Thanks!

**Comment by blainekasten** [comment]
It seems to be working. I downloaded the new version and haven't had an
issue at all. thanks for the quick update! :+1:

**Comment by gisikw** [comment]
Cheers! Pushed a bugfix version update to RubyGems :)
