### ISSUE TITLE
Warning Using Guard 

### ISSUE THREAD

**Issue by imarcelolz** [gisikw/guard-webpack#6]
Hello, I found a bug when using the version 0:12 this project with the guard 2.13.0.
[I made some changes that corrected this problem](https://github.com/imarcelolz/guard-webpack/commit/2147e11c589cba7fc4f39c6c3e25914575c5ad1c).
If you want, I can submit a pull request.

Below are the error information

home/marcelo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-webpack-0.1.2/lib/guard/webpack.rb:2:in `module:Guard': superclass must be a Class (Module given) (TypeError)

**Comment by gisikw** [comment]
Oh, thanks for catching this! If you'd be willing to submit a PR, I'd definitely appreciate it! I'm afraid I'm a bit swamped at the moment, so I might not be able to get to this until next week. Cheers!
